CREATE TABLE `activity_products` (
   `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
   `bn` varchar(255) NOT NULL DEFAULT '' COMMENT '商品编号',
   `barcode` varchar(25) NOT NULL DEFAULT '' COMMENT '商品条形码',
   `name` varchar(255) NOT NULL COMMENT '商品名称',
   `price` int(10) unsigned NOT NULL COMMENT '商品价格',
   `face_value` int(10) NOT NULL DEFAULT '0' COMMENT '面值',
   `marketable` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '上架下架，0=下架，1=上架',
   `cost` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商品成本价格',
   `cat_id` int(10) unsigned NOT NULL COMMENT '商品分类ID',
   `brand_id` int(10) unsigned NOT NULL COMMENT '商品品牌ID',
   `total` int(10) NOT NULL DEFAULT '0' COMMENT '库存',
   `store` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '库存(伙购期数)',
   `limit_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '限购数量,0为不限购',
   `buy_unit` tinyint(1) NOT NULL DEFAULT '1' COMMENT '购买单位',
   `allow_share` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否允许晒单',
   `is_recommend` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否热门推荐',
   `list_order` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
   `brief` varchar(255) DEFAULT '' COMMENT '商品简介',
   `intro` longtext COMMENT '详细介绍',
   `picture` varchar(255) NOT NULL COMMENT '封面图,带后缀的图片名',
   `created_at` int(10) unsigned NOT NULL COMMENT '创建时间',
   `updated_at` int(10) unsigned NOT NULL COMMENT '更新时间',
   `delivery_id` varchar(32) NOT NULL DEFAULT '' COMMENT '发货方式ID',
   `order_manage_gid` int(10) unsigned NOT NULL COMMENT '订单处理小组ID',
   `tag` varchar(255) DEFAULT NULL COMMENT '标签',
   `keywords` varchar(255) DEFAULT NULL COMMENT '关键字',
   `admin_id` int(11) DEFAULT NULL COMMENT '创建人',
   `live_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '使用期限',
   `app` tinyint(1) DEFAULT '0' COMMENT '是否在app上显示',
   `display` tinyint(1) NOT NULL DEFAULT '0' COMMENT '显示地址 0 全部 1火购 2滴滴',
   `activity_id` int(2) NOT NULL DEFAULT '0' COMMENT '活动id',
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB AUTO_INCREMENT=157 DEFAULT CHARSET=utf8 COMMENT='活动商品表'