CREATE TABLE `banners` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(50) NOT NULL COMMENT '名称',
  `source` TINYINT(1) UNSIGNED DEFAULT 0 COMMENT '0终端，1微信，2app',
  `starttime` INT(10) UNSIGNED COMMENT '开始时间',
  `endtime` INT(10) UNSIGNED COMMENT '结束时间',
  `picture` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '图片',
  `link` VARCHAR(100) NOT NULL COMMENT '链接地址',
  `type` TINYINT(1) UNSIGNED DEFAULT 0 COMMENT '位置，0为首页',
  `width` INT(5) UNSIGNED NOT NULL DEFAULT 709 COMMENT '宽度',
  `height` INT(5) UNSIGNED NOT NULL DEFAULT 300 COMMENT '长度',
  `list_order` TINYINT(1) UNSIGNED  DEFAULT '0' COMMENT '排序',
  `created_at` INT(10) UNSIGNED COMMENT '创建时间',
  `updated_at` INT(10) UNSIGNED COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'banner表';