CREATE TABLE `cards` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `number` VARCHAR(50) NOT NULL COMMENT '充值卡号',
  `password` VARCHAR(255) NOT NULL COMMENT '充值密码',
  `money` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '金额',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未售，1已售，2已激活',
  PRIMARY KEY (`id`)
)ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='充值卡';