CREATE TABLE `deliver_fail_reasons` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '发货异常理由',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发货异常';