CREATE TABLE `share_topics` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '晒单话题ID',
  `title` char(80) NOT NULL DEFAULT '' COMMENT '主题',
  `content` text NOT NULL COMMENT '晒单内容',
  `user_id` int unsigned NOT NULL DEFAULT '0' COMMENT '发布者ID',
  `period_id` bigint(8) unsigned NOT NULL DEFAULT '0' COMMENT '期数ID',
  `product_id` INT(10) UNSIGNED NOT NULL COMMENT '商品ID',
  `cat_id` INT(10) UNSIGNED NOT NULL COMMENT '商品分类ID',
  `view_num` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '浏览次数',
  `comment_num` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '回复次数',
  `up_num` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT '羡慕次数',
  `is_recommend` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否推荐',
  `is_digest` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否精华',
  `is_pass` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否通过',
  `created_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发布时间',
  `digested_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '精华时间',
  `recommended_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '推荐时间',
  `header_image` varchar(255) NOT NULL COMMENT '封面图片带后缀的图片名',
  `point` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '福分',
  `note` varchar(256) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`,`created_at`),
  KEY `idx_period_id` (`period_id`,`created_at`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_is_digest` (`is_digest`,`digested_at`),
  KEY `idx_is_recommend` (`is_recommend`,`recommended_at`),
  KEY `idx_is_pass` (`is_pass`,`created_at`),
  KEY `idx_product_id` (`product_id`,`created_at`),
  KEY `idx_cat_id` (`cat_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='晒单话题表';