CREATE TABLE `stats` (
  `date` int(8) NOT NULL COMMENT '日期',
  `reg_num` int(11) NOT NULL DEFAULT '0' COMMENT '注册人数',
  `valid_reg_num` int(11) NOT NULL DEFAULT '0' COMMENT '有效用户',
  `today_reg_recharge` int(11) NOT NULL DEFAULT '0' COMMENT '今日用户充值',
  `today_reg_payment` int(11) NOT NULL DEFAULT '0' COMMENT '今日用户消费',
  `recharge_num` int(11) NOT NULL DEFAULT '0' COMMENT '充值人数',
  `recharge_money` int(11) NOT NULL DEFAULT '0' COMMENT '充值金额',
  `pay_num` int(11) NOT NULL DEFAULT '0' COMMENT '消费人数',
  `pay_money` int(11) NOT NULL DEFAULT '0' COMMENT '消费金额',
  `invite_num` int(11) NOT NULL DEFAULT '0' COMMENT '邀请人数',
  `sign_num` int(11) NOT NULL DEFAULT '0' COMMENT '签到人数',
  `share_lottery` int(11) NOT NULL DEFAULT '0' COMMENT '分享抽奖',
  `recharge_lottery` int(11) NOT NULL DEFAULT '0' COMMENT '充值抽奖',
  `packet_send_num` int(11) NOT NULL DEFAULT '0' COMMENT '红包领取数量',
  `coupon_send_num` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券领取数量',
  `coupon_use_num` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券使用数量',
  `coupon_money` int(11) NOT NULL DEFAULT '0' COMMENT '优惠券抵扣金额',
  `used_point` int(11) NOT NULL DEFAULT '0' COMMENT '消耗福分',
  `add_point` int(11) NOT NULL DEFAULT '0' COMMENT '产生福分',
  `lottery_num` int(11) NOT NULL DEFAULT '0' COMMENT '开奖次数',
  `deliver_num` int(11) NOT NULL DEFAULT '0' COMMENT '发货次数',
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;